data-skeptic/dataskeptic.com

.gitignore
public/css/style.css
shared/components/Episode.js
shared/components/Podcast.js
shared/components/YearNav.js

Changed component styles regarding design.

New podcast page design

---

shared/backend/get_rfc_metadata.js

Fix for backend stub get_rfc_metadata error.

[BACKEND] RFC stub hotfix

---

client/index.jsx
shared/components/BlogList.js
shared/daos/contact_form_send.js

Fixes for some application issues, such as undefined vars, iterations key e.t.c

Application launch fixes

---

client/index.jsx
public/css/style.css
shared/components/AddressForm.js
shared/components/BlogList.js
shared/components/Checkout.js
shared/components/CreditCardForm.js
shared/daos/contact_form_send.js

<details><summary>See in action (PNG)</summary><p>
---
---
</p></details>
<br/>
New checkout page design. 
<br/>
Notes: 
- New checkout page design 
- Checked on mobile/tablet/desktop
- Smart errors design will be implemented later

New checkout page

---

public/css/style.css
server.jsx
shared/Blog/Components/BlogLink.js
shared/Blog/Components/BlogList.js
shared/Blog/Components/BlogNav.js
shared/Blog/Containers/BlogArticle.js
shared/Blog/Containers/BlogContainer.js
shared/Pagination/Containers/PaginationContainer.js
shared/backend/get_blogs.js
shared/components/Episode.js

Changes:
- Added filter by folder on blogs caching
- Pagination component
- Fetching blogs API refactoring
- UI/UX improvements

Blog pagination

---

shared/Blog/Components/BlogListItem.js
shared/components/Episode.js

Client-side fix for old posts links.

Episode redirection fix

---

shared/components/Menu.js
shared/components/NavLink.js

Little UX improvements of active menu item selection.

Main navigation active link improvements

---

public/css/style.css
shared/Contacts/Components/ContactForm/ContactForm.js
shared/Contacts/Routes/ContactUs.js
shared/Forms/Components/Field/Field.js
shared/Forms/Components/FormController/FormController.js

Shared reusable styled Form component.

Shared Form component

---

server.jsx
shared/Pagination/Containers/PaginationContainer.js
shared/backend/get_blogs.js
shared/backend/get_blogs_rss.js

Changes:
- Rss feed security fixes. 
- Fetching blogs list based on env

Pagination fixes

---

shared/Contacts/Helpers/ContactFormValidator/ContactFormValidator.js

Removed `real-name` validation.

Allow Contact Us form to accept any name

---

shared/Blog/Components/BlogList.js
shared/Blog/Components/BlogListItem.js
shared/Blog/Containers/BlogContainer.js
shared/Blog/Reducers/BlogsReducer.js
shared/backend/get_blogs.js

Changes:
- Latest blog post date printing in time from now format
- Api returns latest post id
- Small rendering speed improvements

Several fixes for blog post date issues

---

shared/Blog/Containers/BlogContainer.js
shared/Blog/Routes/BlogRouter.js

Removed navigation links on top of article

Blog article padding fix

---

public/css/style.css
shared/Blog/Containers/LatestEpisodePlayer.js
shared/Cart/Components/CartMenu.js
shared/components/Membership.jsx

Science we redesigned some sections another pages looks inconsistent.   
I make a few changes based on my vision and ideas.
Please confirm changes. Is it OK?
<details><summary>See in action (PNG!)</summary><p>
---
</p></details>

Site styles updates

---

server.jsx

Wrapped refresh function with nextTick

Trying to fix memory issues by next tick function

---

server.jsx
shared/Blog/Actions/BlogsActions.js
shared/Blog/Components/BlogList.js
shared/Blog/Containers/BlogArticle.js
shared/Blog/Reducers/BlogsReducer.js
shared/Podcasts/Components/Episode.js
shared/backend/get_blogs.js
shared/daos/serverInit.js

Fixed blogs ordering and incorrect SSR data generation.

Fixed blog post SSR/little stability fixes/returns.

---

shared/Blog/Reducers/BlogsReducer.js

Hotfix for loading post content.

Fixed blog forever post content loading.

---

global-config.json
package.json
recordingServer.js
server.jsx
shared/Common/Components/Countdown.js
shared/Player/Components/TogglePlayButton.js
shared/Proposals/Components/CommentBoxForm/CommentBoxForm.js
shared/Proposals/Components/ProposalLoading/ProposalLoading.js
shared/Proposals/Containers/CommentBoxContainer/CommentBoxFormContainer.js
shared/Proposals/Helpers/CommentFormValidator/CommentFormValidator.js
shared/Proposals/Routes/Proposals.js
shared/Recorder/Containers/RecorderFlowContainer/RecorderFlowContainer.js
shared/daos/serverInit.js
shared/styles/pages/_proposals.less

Note: please install `ffmpeg` locally and install on the server

Proposal ui updates

---

shared/Cart/Components/CartItem.js
shared/Cart/Containers/CartContainer.js
shared/Cart/Reducers/CartReducer.js

Fixed cart item removing logic

DATS-42 Cart delete removes wrong item

---

shared/Blog/Actions/BlogsActions.js
shared/Blog/Containers/BlogArticle.js
shared/Blog/Reducers/BlogsReducer.js

Using api v1 introducing not found blog post page.

Added not found blog post catching page

---

backend/modules/Player/Services/MetaDataService.js
shared/Player/Components/MiniPlayer.js
shared/Player/Containers/PlayerContainer.js
shared/reducers/SiteReducer.js

Added fields timestamp guid and listenerID to meta, which are sending to dynamoDB, also guid and listenerID right now writing to local storage

Player Metadata Improvements 

---

shared/Contacts/Components/ContactForm/ContactForm.js
shared/Contacts/Containers/ContactFormContainer/ContactFormContainer.js
shared/Contacts/Routes/ContactUs.js
shared/reducers/SiteReducer.js

Fix contact form submit button

Fix Contact Form submitting button

---

Dockerfile
package.json

FIxed DockerFile instructions. 
It should be Label maintener instruction instead MAINTER, and in dockerfile must be only one CMD instruction, so I created script docker_start, that starts two another scripts

Docker file

---

backend/api/v1/auth.js
backend/api/v1/index.js
backend/modules/Auth/GoogleStrategy.js
backend/modules/Auth/LinkedinStrategy.js
backend/modules/Auth/index.js
backend/modules/rfc/services/rfcService.js
package.json
server.jsx
shared/Proposals/Actions/ProposalsActions.js
shared/Proposals/Reducers/ProposalsReducer.js
shared/Proposals/Routes/Proposals.js
shared/Proposals/Routes/ProposalsHandler/ProposalsHandler.js
shared/reducers/SiteReducer.js
shared/routes.jsx

I fixed auth module, cause I found mistakes there, like broken linkedin callback, and also created GoogleStrategy and done routing for it. Also I figured out mistakes in your reducer, that crashed your /rfc page

Google OAuth on RFC page 

---

shared/Blog/Containers/BlogArticle.js
shared/Blog/Reducers/BlogsReducer.js

Probably found some reason when it failed sometimes.

Real blog post data fetching fix

---

shared/Privacy/Components/PrivacyText.js
shared/Privacy/Containers/PrivacyPageContainer.js
shared/routes.jsx

I have a question, I've added a new privacy page, but  I have a question: where is the link to this page should be located?

Add privacy page

---

shared/Contacts/Containers/ContactFormContainer/ContactFormContainer.js
shared/Proposals/Reducers/ProposalsReducer.js
shared/Proposals/Routes/Proposals.js
shared/Wizard/Containers/WizardContainer.js
shared/styles/pages/_proposals.less

RFC login access fix

---

shared/Layout/Components/Footer/Footer.js
shared/components/index.jsx
shared/routes.jsx

Fixes #173
To make page Ad-Free use `showAd = {false}` prop for `<Route/>` component

Ad-Free pages

---

lambdaForSlack/README.md
lambdaForSlack/index.js
lambdaForSlack/package.json
lambdaForSlack/policies/lambda_execute_policy.json

Before starting working with claudia.js you need to install and configure it.
Claudia is an npm package, so you can install it by executing next command:
npm i -g claudia
Then you have to go to your home directory on you computer (cd ~/) and create there directory
.aws, and create file credentials into it (mkdir .aws && cd .aws && touch credentials)
credentials file has next format:
[claudia]
aws_access_key_id = YOUR_ACCESS_KEY
aws_secret_access_key = YOUR_ACCESS_SECRET
Then save it, and now, you are able to work with claudia.js
1. First you need to create webhook in your slack API. Go to https://api.slack.com/apps
2. On this page you need to create new app, related to your team, or choose existed
3. Then, in left menu you need to choose Incoming Webhooks. Then, on the bottom of page …

Lambda functions managing / Slack notification Lambda

---

shared/Forms/Components/FormController/FormController.js
shared/Proposals/Actions/CommentBoxFormActions.js
shared/Proposals/Components/CommentBoxForm/CommentBoxForm.js
shared/Proposals/Components/UploadFileTypeBox/UploadFileTypeBox.js
shared/Proposals/Containers/CommentBoxContainer/CommentBoxFormContainer.js
shared/Proposals/Helpers/CommentFormValidator/CommentFormValidator.js
shared/Proposals/Reducers/ProposalsReducer.js
shared/Recorder/Components/Recorder/Recorder.js
shared/Recorder/Containers/RecorderFlowContainer/RecorderFlowContainer.js
shared/styles/framework/_recording.less

Fix #187 
Added some error checks for submitting all types of proposals and fix form validation

Rfc error catch

---

recordingServer.js
server.jsx
shared/backend/v1/proposals.js

There is a strange thing with config read and `missing credentials` issue.
It happenes because fs.open is an async operation and sometimes it's executes slower then we trying to access DynamoDB to fill the cache

Sync config loading

---

backend/modules/Auth/GoogleStrategy.js

Fixed google strategy config for production

---

recordingServer.js
recordingUtils.js
server.jsx
shared/Proposals/Containers/CommentBoxContainer/CommentBoxFormContainer.js
shared/Recorder/Containers/RecorderFlowContainer/RecorderFlowContainer.js
shared/backend/v1/proposals.js
shared/backend/v1/recording.js

Recording flow improvements 

---

server.jsx

Fixed production recording

---

package.json
shared/Proposals/Actions/CommentBoxFormActions.js
shared/Proposals/Actions/RecordingFlowActions.js
shared/Proposals/Containers/CommentBoxContainer/CommentBoxFormContainer.js
shared/Proposals/Reducers/ProposalsReducer.js
shared/Recorder/Containers/RecorderFlowContainer/RecorderFlowContainer.js

Confirmation UI

---

server.jsx
views/index.ejs

Fixes #219 
Requires insert this line to dev/prod config file

Initial iTunes link commit

---

recordingUtils.js
shared/Contacts/Containers/ContactFormContainer/ContactFormContainer.js

Fixed warning

---

backend/modules/Player/Services/MetaDataService.js

Fixed production error

---

backend/api/v1/mail.js
backend/modules/mail/services/MailServices.js
shared/Contacts/Containers/ContactFormContainer/ContactFormContainer.js

I hope this is going to be last one. 
I'm sending data to email lambda in this format: 
```
{
msg: "<html>email_template</html>"
}
```
If I try to send plain html template to lambda, I get this error
```Could not parse request body into json: Unexpected character```

Contact Email 

---

backend/api/v1/blog.js
backend/api/v1/episodes.js
backend/api/v1/index.js
backend/api/v1/store.js
backend/modules/blog/services/BlogServices.js
server.jsx
shared/Blog/Containers/LatestEpisodePlayer.js
shared/Blog/Reducers/BlogsReducer.js
shared/Blog/Routes/BlogRouter.js
shared/daos/serverInit.js
shared/utils/redux_loader.js

That should fix the conflicts after the PR https://github.com/data-skeptic/dataskeptic.com/pull/273, https://github.com/data-skeptic/dataskeptic.com/pull/272

Cache and Episodes Conflicts Resolving

---

backend/api/v1/blog.js
backend/modules/blog/models/BlogItem.js
backend/modules/blog/services/BlogServices.js

RSS format fixes

---

shared/styles/components/_player.less

Fixes player title glitching

---

server.jsx

Soft cache reset

---

backend/api/v1/auth.js
server.jsx
shared/components/Login.js
shared/components/Logout.js
shared/components/MembershipPortal.js
shared/routes.jsx

Initial Login Page

---

shared/Analytic/Analytic.js
shared/styles/cms/cms.less
shared/styles/main.less

CMS less file and initialize simple `Analytic` components

Analytic component.

---

shared/Analytic/Analytic.js
shared/components/Analytics.js
shared/routes.jsx

Available at `/analytics` route.

Analytics page

---

shared/Layout/Components/Footer/Footer.js

Itunes link fix

---

shared/SnsUtil.js
shared/reducers/AdminReducer.js
shared/reducers/MemberPortalReducer.js
webpack.dev.js

Set env variable at client side

---

shared/components/MembershipPortal.js

Returns dispatch at props

---

shared/Layout/Components/Footer/Footer.js
shared/routes.jsx

Disabled ad on members page

---

shared/Blog/Components/BlogItem.js
shared/Blog/Routes/BlogRouter.js
shared/reducers/CmsReducer.js

Fixes #341 
**Solution:**
Use `blog_state` param to control post loading(loaded?) state

Remove loading gap on blog loading

---

shared/Common/Components/MailingList.js

Fixes #306 
**Reason:**
Input lose component context, so `this` is undefined and `setState` function couldn't be called.

Mailing onChange error fix

---

shared/Blog/Components/BlogList.js
shared/Blog/Components/BlogListItem.js

Fixes #298
**Solution:** 
Use existing contributors list fetched on the server to extract data for needed author.

Blog contributor data

---

shared/components/Store.js
shared/components/StoreItem.js
shared/styles/pages/_store.less

Store Redesign

---

shared/Proposals/Routes/Proposals.js
shared/components/About.js

Fixes #360
**Solution:** 
Retrieve contributors list from the `site` reducer and display them one by one.

Contributors List at About Page

---

shared/Home/Content/Podcast/style.js

Added cursor pointer to play button

add cursor pointer to play button

---

shared/Cart/Components/AccountDropdownMenu.js
shared/Cart/Components/CartMenu.js
shared/MobileMenu/Components/MobileMenu.js
shared/components/Header.jsx
shared/components/index.jsx
shared/styles/layout/_header.less
shared/styles/layout/_sidebar.less

Fixes #397
**Desktop**
**Mobile**

Navigation account section

---

shared/Podcasts/Components/Episode.js
shared/Podcasts/Components/GuestImage.js
shared/styles/pages/_podcasts.less
shared/utils/redux_loader.js

Guest images

---

index.js

Enable Recording server at production 

---

server.jsx
shared/Home/Content/Blog/index.js
shared/Home/Content/Blog/style.js
shared/Home/Content/Feature/index.js
shared/Home/Content/index.js
shared/components/EpisodePlayer.js
shared/components/GuestImage.js
shared/reducers/CmsReducer.js

Home author images

---

shared/reducers/EpisodesReducer.js
shared/utils/redux_loader.js

Fixes #421 
**Solution**
Dispatching preloading action for episodes before each loading request.

Loading screen on Podcast page

---

backend/api/v1/auth.js

Send email notification on join

---

client/index.jsx
server.jsx
shared/Blog/Components/BlogAuthorBottom.js
shared/Blog/Components/BlogAuthorTop.js
shared/Blog/Components/BlogListItem.js
shared/Contributors/Routes/ContributorPage.js
shared/components/AuthorLink.js
shared/reducers/SiteReducer.js
shared/routes.jsx
shared/utils/redux_loader.js

Contributors page

---

shared/components/admin/AdminOrdersNew.js
shared/components/admin/OpenOrders.js
shared/components/admin/Order.js
shared/components/admin/OrderProcessing.js

Redirect on populate button click 

---

server.jsx
shared/Blog/Components/BlogItem.js
shared/Blog/Components/BlogList.js
shared/Blog/Components/BlogListItem.js
shared/Contributors/Routes/ContributorPage.js
shared/styles/pages/_blog.less
shared/utils/redux_loader.js

Fixes #431, #430
Insert after 2nd paragraph an image in case its exist
Display preview at blog list/contributor page

Blog post image

---

backend/api/v1/auth.js

Current dev is broken by some updates

Email notification hotfix

---

shared/Contributors/Routes/ContributorPage.js

Don't show links to nowhere

---

shared/Blog/Components/BlogListItem.js
shared/Contributors/Routes/ContributorPage.js

Don't indent blog if no preview exist

---

recordingServer.js

Should fix site crash for a moment

Recording crash hotfixes 

---

shared/Home/Content/Blog/index.js
shared/Home/Content/Feature/index.js
shared/Home/Content/Feature/style.js

HomePage contributors links

---

shared/Contributors/Routes/ContributorPage.js
shared/Home/Content/Feature/index.js
shared/Home/Content/Feature/style.js
shared/components/About.js
shared/components/AuthorLink.js
shared/reducers/SiteReducer.js

Contributors improvements 

---

backend/api/v1/auth.js
shared/Cart/Components/AccountDropdownMenu.js
shared/Cart/Components/CartMenu.js
shared/MobileMenu/Components/MobileMenu.js
shared/components/Header.jsx
shared/components/index.jsx

Admin link at account dropdown 

---

shared/components/admin/HomepageController.js
shared/reducers/CmsReducer.js

Homepage feature saving

---

shared/Contacts/Routes/ContactUs.js
shared/Questions/Forms/QuestionForm.js

Question recorder form validation

---

shared/components/About.js

Added sorting at contributors page

---

shared/Contacts/Containers/ContactFormContainer/ContactFormContainer.js

Fixed Email endpoint url

---

shared/components/About.js

Sort contributors by correct key

---

views/index.ejs

Favicon Fix

---

package.json
shared/Cart/Components/CartMenu.js
shared/Search/Components/SearchField.js
shared/Search/Containers/MobileSearchArea.js
shared/Search/Containers/SERP.js
shared/Search/Containers/SearchArea.js
shared/Search/Helpers/redirectToSearch.js
shared/components/Menu.js
shared/reducers/SearchReducer.js
shared/routes.jsx
shared/styles/components/_search.less
shared/styles/main.less

Search Page

---

shared/Search/Containers/SERP.js

Search Result Empty Data 

---

backend/api/v1/auth.js
shared/Auth/Reducers/AuthReducer.js
shared/Search/Containers/SERP.js
shared/components/Login.js
shared/components/Logout.js
shared/components/MembershipPortal.js
shared/components/SignUp.js

Login/Logout user without refreshing the page.
Auto register on join using Google

Auth module improvements

---

shared/daos/serverInit.js

Fixed libsyn http link

---

shared/components/admin/AdminLayout.js

Critical bug fix

---

shared/Contacts/Routes/ContactUs.js

Fixed contact us error layout

---

shared/Common/Components/MailingList.js
shared/styles/pages/_home.less

New Subscribe form layout

---

shared/components/admin/BlogSearchSelect.js
shared/components/admin/HomepageController.js
shared/components/admin/RelatedContent.js
shared/styles/components/_search.less

Content Select Field

---

shared/reducers/CmsReducer.js

Populate home latest episode from the cache

---

backend/api/v1/auth.js
backend/api/v1/user.js

Improved user type detection

---

build/fixes.sh
shared/Recorder/Containers/RecorderFlowContainer/RecorderFlowContainer.js

Remove blank space

---

backend/api/v1/download.js
backend/api/v1/index.js
backend/api/v1/user.js
shared/Cart/Components/AccountDropdownMenu.js
shared/components/Login.js
shared/components/SignUp.js
shared/components/membership/MembershipDownloads.js
shared/components/membership/MembershipHeader.js
shared/reducers/MemberPortalReducer.js
shared/reducers/SiteReducer.js
shared/routes.jsx
shared/styles/main.less

Download area

---

shared/Cart/Components/CartMenu.js
shared/Contributors/Routes/ContributorPage.js
shared/Home/Content/Blog/style.js
shared/Home/Content/Feature/style.js
shared/styles/components/_search.less

Design updates

---

shared/Blog/Components/MailingListBlogFooter.js
shared/Common/Components/MailingList.js
shared/styles/pages/_blog.less

Blog page subscribe form styles

---

shared/Checkout/Actions/CheckoutActions.js

Checkout process fixes [TESTING]

---

package.json
server.jsx
shared/daos/serverInit.js

Rollbar server configuration

---

backend/api/v1/jobs.js
backend/api/v1/jobs_util.js
server.jsx
shared/components/Home.jsx
shared/daos/serverInit.js
shared/reducers/CmsReducer.js

Home load errors

---

backend/api/v1/career.js
backend/api/v1/index.js
backend/api/v1/jobs_util.js
shared/Forms/Components/Field/Checkbox.js
shared/Forms/Components/Field/index.js
shared/Jobs/Forms/UploadResume.js
shared/Jobs/Routes/Careers.js
shared/Proposals/Components/UploadFileTypeBox/UploadFileTypeBox.js
shared/reducers/JobsReducer.js
shared/reducers/index.js
shared/routes.jsx
shared/styles/pages.less
shared/styles/pages/_career.less

Careers page [WIP]

---

build/fixes.sh
server.jsx
shared/Home/Content/JobListing/index.js
shared/Tracking/hoc/trackable.js

Tracking `Real` job impression

---

backend/api/v1/career.js
package.json
shared/Jobs/Forms/UploadResume.js
shared/Jobs/Routes/Careers.js
shared/backend/v1/proposals.js
shared/reducers/JobsReducer.js

Fixes #525 
Please update `config` file.
``` 
"careers": {
"filesBucket": "bucket",
"email": "notification eamil"
},
```

Careers page resume upload/notification

---

shared/styles/main.less

Update links styles

---

shared/Home/Content/JobListing/index.js
shared/Tracking/hoc/trackable.js

Fixes decorator `dev` branch issue

Remove decorators

---

shared/Contributors/Routes/ContributorPage.js

Contributors page markdown

---

shared/styles/pages/_blog.less

Fixed blog page mail from transparent color text

---

shared/Blog/Components/BlogAuthorBottom.js
shared/Blog/Components/BlogAuthorTop.js
shared/Blog/Components/BlogListItem.js
shared/Contacts/Routes/ContactUs.js
shared/Contributors/Routes/ContributorPage.js
shared/Home/Content/Blog/index.js
shared/Home/Content/Blog/style.js
shared/Home/Content/Feature/index.js
shared/Home/Content/Feature/style.js
shared/Podcasts/Components/Episode.js
shared/components/About.js
shared/components/AuthorLink.js
shared/components/EpisodePlayer.js
shared/styles/main.less

Following  #572 suggestions update links logic. 
General links will be underlined.
Images and headlines just have nice smooth color change animation to primary color (now purple) 
Color animation

Link styles

---

shared/Contacts/Components/SectionBlock/SectionBlock.js
shared/Contacts/Routes/ContactUs.js
shared/Recorder/Containers/RecorderContainer/RecorderContainer.js
shared/Recorder/Containers/RecorderFlowContainer/RecorderFlowContainer.js
shared/styles/framework/_recording.less

Fixes #567
Also replaced recording text

Replaced icons to the s3 links

---

shared/Jobs/Routes/Careers.js
shared/styles/pages/_career.less

Careers page column layout

---

backend/api/v1/files.js
backend/api/v1/index.js
shared/Forms/Components/DragAndDropFileUploadField.js
shared/Forms/Components/Field/Field.js
shared/Forms/Components/FilePreview.js
shared/Forms/Components/ImageUploadField.js

Deliver shared component for `Drag & Upload File field` and endpoint to handle that upload to s3

File upload field [order-1]

---

backend/api/v1/career.js
shared/Jobs/Forms/UploadResume.js

Careers updates

---

shared/Jobs/Routes/Careers.js

Careers countdown

---

backend/api/v1/orders.js

Production Keys for checkout 

---

backend/api/v1/download.js

Download Area bug fix 

---

shared/Chat/Containers/Launcher.js

Mobile Responsive Layout for ChatBot

---

shared/Chat/Containers/Launcher.js
shared/components/index.jsx

Chatbot Inactive Fix

---

shared/Checkout/Actions/CheckoutActions.js

Orders email fake error 

---

shared/Emails/templates/contact.ejs

Fixes contact us template space char

---

shared/Chat/Containers/UserInput.js

Focus mobile keyboard after chatbot input submit

---

shared/Chat/Components/Message/index.js

Latest mobile chat changes a little broke a message layout (avatar float/margin). This PR resolve it.

Fixed desktop message view

---

server.jsx

Session persist fixes

---

shared/Checkout/Actions/CheckoutActions.js
shared/backend/add_order.js

Provide human-readable errors to the client from the server.

Checkout error

---

shared/Jobs/Containers/Events/index.js
shared/Jobs/Routes/CityCareers.js

Careers City page bugs

---

shared/Jobs/Forms/AddJob.js
shared/components/admin/AdminAddJob.js

Add job form updates

---

client/index.jsx
shared/Player/Containers/PlayerContainer.js
shared/components/EpisodePlayer.js
shared/reducers/PlayerReducer.js

Remember mp3 player

---

shared/Blog/Components/BlogItem.js
shared/Blog/Components/BlogShareBar.js
shared/Blog/Routes/BlogRouter.js
shared/styles/cms/cms.less
shared/styles/pages/_blog.less

Fixes #626 
<details><summary>Desktop</summary><p>
---
---
</p></details>
<details><summary>Mobile</summary><p>
---
</p></details>

Update blog css

---

shared/Chat/Containers/Launcher.js
shared/Chat/Reducers/ChatbotReducer.js
shared/components/index.jsx

Inactive message updates

---

shared/backend/add_order.js

Checkout Advanced Error Catching

---

server.jsx

Cache ipInfo Error 

---

shared/Player/Containers/PlayerContainer.js

Rollbar Issues Fixes

---

shared/Player/Components/MiniPlayer.js
shared/Player/Containers/PlayerContainer.js
shared/reducers/PlayerReducer.js
shared/styles/components/_player.less

Close player feature

---

shared/Blog/Components/NoBlogs.js
shared/Blog/Routes/BlogRouter.js

Normalize Incorrect Blogs Urls

---

shared/reducers/PlayerReducer.js

Player Logic Improvements

---

shared/reducers/AdminReducer.js

Handle Error at Add Related Content

---

shared/Podcasts/Routes/Podcast.js

Mocked episode attributes on case they are empty

---

shared/Forms/Components/RichTextarea.js
shared/Jobs/Forms/AddJob.js
shared/styles/components/_forms.less

Improve description styles and height

---

server.jsx
shared/Player/Components/MiniPlayer.js
shared/Player/Components/PlayerProgressBar.js
shared/Player/Components/TogglePlayButton.js
shared/Player/Components/VolumeBar.js
shared/Player/Containers/PlayerContainer.js
shared/Player/Containers/VolumeBarContainer.js
shared/Recorder/Containers/RecorderFlowContainer/RecorderFlowContainer.js
shared/reducers/PlayerReducer.js
shared/styles/components/_player.less

Player Bugfixes

---

shared/Podcasts/Components/Episode.js
shared/reducers/PlayerReducer.js

Fix https player issue

---

index.js
package-lock.json
package.json
recordingServer.js
recordingUtils.js
server.js
server.jsx
shared/Contacts/Routes/ContactUs.js

recording component restore

---

shared/Search/Components/SearchField.js
shared/Search/Containers/SERP.js
shared/styles/components/_search.less

- Fixed second search not working issue
- Added search key clear button in front of the search keyword
- changed the page title in second search

Fix second search issue, add search key clear button, change page title

---

package.json
shared/Search/Containers/SearchArea.js
shared/styles/components/_search.less

Header search area has been worked as page reload
modified codebase to make search without reload the page - SPA feature

main search without page reload

---

package.json
shared/Contacts/Routes/ContactUs.js

- Fixed build issue by installed `bucket-blog`
- Removed mailchimp signup from ContactUs page.

Fixed build, and removed mailchimp from contact

---

shared/utils/checkEnv.js

- Changed config to allow empty env values.

removed env validation

---

shared/Cart/Components/CartMenu.js

commented out store link

---

index.js

updated google ads
